name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Set up Python 3.8
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e  # v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: pip install black
    - name: Run Quality check
      run: make quality
